

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: murad
    password: password
  flyway:
    user: murad
    password: password
    url: jdbc:postgresql://localhost:5432/spring_reactive
server:
  port: 8081
